### ISSUE TITLE
Parskip inserting negative space between LoT/F title and items

### ISSUE THREAD

**Issue by tomh-overleaf** [FrankMittelbach/fmitex#12]
Minimal example:

```
\documentclass{article}

\usepackage[skip=20pt]{parskip}

\begin{document}

\listoffigures

\begin{figure}
\caption{This is first figure}
\end{figure}

\begin{figure}
\caption{This is second figure}
\end{figure}

\end{document}
```

The title "List of Figures" overlaps with "1 This is first figure". This is confirmed in TeX Live 2018, 2019, 2020. Originally reported at https://tex.stackexchange.com/q/544880/11002

**Comment by FrankMittelbach** [comment]
thanks, clearly a bug, but it is there since day one (if that is an excuse :-) only that n older versions of parskip it wasn't so noticable, because you couldn't set the skip to such large values so it wasn't actually overlapping (only shortening the distance by half a baselineskip. I'll see what I can do.

**Comment by FrankMittelbach** [comment]
Try
```
\usepackage[skip=20pt]{parskip}

\makeatletter
\patchcmd\@starttoc
    {\parskip\z@}
    {\vskip\parskip\parskip\z@ }
    {}{\typeout{Couldn't patch \string\@starttoc}}
\makeatother
```
as a workaround at the moment until fixed version is on CTAN

**Comment by FrankMittelbach** [comment]
on the way to ctan
