### ISSUE TITLE
Problem with fewerfloatpages, lscape and specific eps include

### ISSUE THREAD

**Issue by paultjevdh** [FrankMittelbach/fmitex#13]
Hi
This month I read in tugboat about your new package fewerfloatpages. I immediately started using it and I'm happy with it so far.
I did run into a problem though with the combination of fewerfloatpages, lscape and a specific eps figure.

Please see the attached MWE. 

As you can see, the tex file can include two eps figures. 
- If only the first is active, the document compiles fine. 
- If instead the second one is active, I get the error: "Output loop---100 consecutive dead cycles. \end{landscape}"
You could argue that the second eps file is probably corrupt, but 
- when I remove the landscape environment, the document compiles fine with the second figure.
- Also, when I keep the landscape environment but do not include the fewerfloatpages package, the file compiles fine. 

This is the reason I had no problems until I used the new package. The problem is in the combination of the three.

I hope you understand what is going on...

Best regards,
Paul van der Hulst

I run plain latex.exe from an updated MikTeX distribution
[demo.zip](https://github.com/FrankMittelbach/fmitex/files/4695848/demo.zip)

**Comment by FrankMittelbach** [comment]
> This month I read in tugboat about your new package fewerfloatpages. I immediately started using it and I'm happy with it so far.

good. the issue you list is truely weird but it has nothing to do with your figures just doing
```
\begin{landscape}
	\begin{figure}
  XXX
	\end{figure}
\end{landscape}
```
triggers it, so it has to do with the page being not full enough. 

The isssue is that lscape remembers the definition of \@makefcolumn when it is loaded and uses that one. But makefewerfloatpages changes the definition because during a clearpage it has to change behavior. But it does so only after begin document  (for a number of reasons) so basically lscape uses the saved (wrong) definition. As a result we get the float unraveled when it shouldn't be unraveled (you can see this if you use the option "trace") and it is sort of discussed in the package documentation.

Immediate workaround:  use explicitly `[p]` for your figure so that it is never been unraveled.
As to how we can make the packages work together I have to discuss this with @davidcarlisle how to best make this happen.

**Comment by davidcarlisle** [comment]
I suppose we could just move

`\let\LS@makefcolumn=\@makefcolumn`

from the top level into the definition of `\landscape` ?

**Comment by FrankMittelbach** [comment]
Am 28.05.20 um 17:03 schrieb David Carlisle:
> I suppose we could just move
> 
> |\let\LS@makefcolumn=\@makefcolumn|
> 
> from the top level into the definition of |\landscape| ?

that should do it and is probably better than me trying to overwrite 
\LS@makefcolumn at begin document

**Comment by FrankMittelbach** [comment]
one could think I have quoted very rude words :-)

**Comment by paultjevdh** [comment]
I understand nothing of what you're talking about, but I'm very glad it was picked up so fast.
Thanks very much, also for the [p] workaround. Works for me.

Best regards,
Paul van der Hulst

**Comment by FrankMittelbach** [comment]
Given that there is a workaround for now (using `[p]`) I'll close this here. It will be addressed in lscape which will see a new release in fall.
