### ISSUE TITLE
Incompatibility with the revtex4

### ISSUE THREAD

**Issue by Togo-95** [FrankMittelbach/fmitex#4]
There is some issue with the revtex4 document class. 

Using the following test file:
```
\documentclass{revtex4}
\usepackage{parskip}

\begin{document}
	\tableofcontents
	\section{Introduction}
\end{document}
```
I get this error message:

> ! Missing number, treated as zero.
>                    \tocleft@section 
> l.4 ...{section}{\numberline {I}Introduction}{1}{}

Both using a different document class and not using the parskip package resolve the issue.

**Comment by FrankMittelbach** [comment]
That is interesting. Could i please get the full `.log` file attached because I don't see this error message here. I see it only if I run the old `parskip.sty `which you get when you run the new one with

`\usepackage{parskip}[=v1]`

in short it looks to me as if `parskip` was never compatible with revtex4 (which isn't really surprising if a class changes a lot of internals and parskip is meant to patch the default classes and their code)

**Comment by FrankMittelbach** [comment]
no feedback received, so close
